language: python
python:
  - "3.6"
  - "3.7"
# install dependencies
install:
  - pip install -r requirements.txt
# tests
script:
  - pytest
env:
  - CODECOV_TOKEN="8628ff6f-6246-49ab-bb35-9edf85ea6a81"
